version: '3'
services:
  frontend:
    build: ./frontend
    environment:
      PORT: 8080
      AUTH_API_ADDRESS: http://auth-api:8081
      TODOS_API_ADDRESS: http://todos-api:8082
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - 8080:8080
    depends_on:
      - zipkin
      - auth-api
      - todos-api
      - users-api
    restart: unless-stopped

  auth-api:
    build: ./auth-api
    image: auth-api
    environment:
      AUTH_API_PORT: 8081
      JWT_SECRET: myfancysecret
      USERS_API_ADDRESS: http://users-api:8083
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
      - users-api
    restart: unless-stopped

  todos-api:
    build: ./todos-api
    image: todos-api
    environment:
      JWT_SECRET: myfancysecret
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - 8082:8082
    volumes:
      - ./todos-api/src:/src
    depends_on:
      - zipkin
      - redis-queue
      - todos-api-db-1
      - todos-api-db-2
      - todos-api-db-3
    restart: unless-stopped

  todos-api-db-1:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGODB_DATABASE: test
      MONGODB_USERNAME: api
      MONGODB_PASSWORD: api
    volumes:
      - ./todos-api/initDB.js:/initDB.js
      - ./todos-api/setupDBCluster.js:/setupDBCluster.js
    expose:
      - 27017
    restart: unless-stopped
    depends_on:
      - todos-api-db-2
      - todos-api-db-3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  todos-api-db-2:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGODB_DATABASE: test
      MONGODB_USERNAME: api
      MONGODB_PASSWORD: api
    expose:
      - 27017
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  todos-api-db-3:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: test
      MONGODB_DATABASE: test
      MONGODB_USERNAME: api
      MONGODB_PASSWORD: api
    expose:
      - 27017
    restart: unless-stopped
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  users-api:
    build: users-api
    environment:
      JWT_SECRET: myfancysecret
      ZIPKIN_BASE_URL: http://zipkin:9411
      DATABASE_URL: postgres://api:api@users-api-db:5432/main
    depends_on:
      - zipkin
      - users-api-db
    volumes:
      - ./users-api/src:/src
    expose:
      - 8083
    restart: unless-stopped

  users-api-db:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      POSTGRES_DB: main
    restart: unless-stopped

  log-message-processor:
    build: ./log-message-processor
    image: log-message-processor
    environment:
      REDIS_HOST: redis-queue
      REDIS_PORT: 6379
      REDIS_CHANNEL: log_channel
      ZIPKIN_URL: http://zipkin:9411/api/v1/spans
    depends_on:
      - zipkin
      - redis-queue
    restart: unless-stopped
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    restart: unless-stopped

  redis-queue:
    image: redis
    restart: unless-stopped